version: "3.8"
services:
  tsundoku:
    image: tylergibbs2/tsundoku
    container_name: tsundoku
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - <path to config file>:/app/config.ini
      - <path to parser folder>:/app/parsers
      - <path to downloaded>:/downloaded
      - <path to target location>:/target
    ports:
      - "6439:6439"
    depends_on:
      - <replace this with your postgres docker service name>
    restart: unless-stopped